services:

  cinema_db:
    image: postgres:latest
    container_name: cinema_db
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "cinema_db_data:/var/lib/postgresql/data"
    restart: unless-stopped

  keycloak_db:
    image: postgres:latest
    container_name: ${KEYCLOAK_DB}
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - "keycloak_db_data:/var/lib/postgresql/data"
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: info

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}

    command: start-dev
    depends_on:
      - keycloak_db
    ports:
      - "8080:8080"
    restart: unless-stopped


volumes:
  cinema_db_data:
  keycloak_db_data:

